### ISSUE TITLE
zero_gradients cannot be imported

### ISSUE THREAD

**Issue by jessicapol** [ShawnLixx/nest_your_adaptive_minimax#1]
The code does not run because of the following error message:
ImportError: cannot import name 'zero_gradients' from 'torch.autograd.gradcheck'

 Probably, it was removed as part of a refactor to the code.

**Comment by ShawnLixx** [comment]
Yes, it is deprecated in newer versions of PyTorch. The implementation of this function is easy (https://discuss.pytorch.org/t/from-torch-autograd-gradcheck-import-zero-gradients/127462).
